[package]
name = "personal"
version = "0.1.0"
authors = ["Maxim Avanov <maxim.avanov@gmail.com>"]

[dependencies]
actix = "0.7.5"
actix-web = "0.7.13"
diesel = { version = "1.3.3", features = ["postgres"] }
dotenv = "0.13.0"